title: <p align="center"> Varun Karkera </p>
logo: /assets/img/VARUN_PIC.jpg

description:
  <p align="center">
  <a href="https://www.linkedin.com/public-profile/settings?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_self_edit_contact-info%3BLc1efPlEQQaHbiFZuXxJZg%3D%3D">LinkedIn</a> |
  <a href="https://github.com/vkarkera">GitHub</a>
  
  <br>   
  I'm currently doing my Post Graduation in Machine Learning and Artificial Intelligence from IIIT Bangalore.
  <br>
  </p>

